version: "3"
services:
  node1:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app
    container_name: node1
    environment:
      - PORT=3000
  node2:
    build: .
    ports:
      - "3001:3000"
    volumes:
      - ./src:/app
    depends_on:
      - node1
    container_name: node2
    environment:
      - PORT=3000
      - INITIAL_PEER_ADDRESS=node1
      - INITIAL_PEER_PORT=3000
  node3:
    build: .
    ports:
      - "3002:3000"
    volumes:
      - ./src:/app
    depends_on:
      - node1
    container_name: node3
    environment:
      - PORT=3000
      - INITIAL_PEER_ADDRESS=node1
      - INITIAL_PEER_PORT=3000
